arrowParens: always
bracketSpacing: false
endOfLine: lf
printWidth: 80
ignorePath: .prettierignore
proseWarp: always
quoteProps: as-needed
semi: false
singleQuote: false
tabWidth: 2
trailingComma: all
useTabs: false
vueIndentScriptAndStyle: true
